CREATE TABLE IF NOT EXISTS Details
(
    Serial          INTEGER AUTO_INCREMENT PRIMARY KEY,
    Capacity        CHARACTER LARGE OBJECT NOT NULL,
    PowerPlants     CHARACTER LARGE OBJECT NOT NULL,
    Performance     CHARACTER LARGE OBJECT NOT NULL,
    Type            CHARACTER LARGE OBJECT NOT NULL,
    Dimensions      CHARACTER LARGE OBJECT NOT NULL,
    RelatedAircraft CHARACTER LARGE OBJECT NOT NULL,
    CountryOrigin   CHARACTER LARGE OBJECT NOT NULL,
    Weights         CHARACTER LARGE OBJECT NOT NULL,
    History         CHARACTER LARGE OBJECT NOT NULL,
    Name            CHARACTER LARGE OBJECT NOT NULL,
    Production      CHARACTER LARGE OBJECT NOT NULL
);

